export const GET_FAVORITE_SERIES = "GET_FAVORITE_SERIES";
export const POST_FAVORITE_SERIE = "POST_FAVORITE_SERIE";
export const DELETE_FAVORITE_SERIE = "DELETE_FAVORITE_SERIE";
export const REMOVE_FAVORITE_SERIE = "REMOVE_FAVORITE_SERIE"